#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh

cd iniciarSesion
npm run format:check
npm run lint:check
#npm run test
cd ..
cd registrarUsuario
npm run format:check
npm run lint:check
#npm run test
